var uiStringsHu = {
  "empty-str": "",
  "tooltip-btn-brush": "Kézírás-felismerés",
  "tooltip-btn-settings": "Keresési beállítások",
  "tooltip-btn-search": "Keresés a CHDICT-ben (Enter)",
  "no-animation-for-char": "Ehhez az írásjegyhez sajnos nincs vonássorend-animáció.",
  "anim-query-failed": "Nem sikerült betölteni az írásjegyhez tartozó vonássorrend-animációt.",
  "anim-attribution": "Forrás: <a href='https://skishore.github.io/makemeahanzi/' target='_blank'>makemeahanzi</a>",
  "anim-title": "Vonássorrend",
  "options-title": "Keresési beállítások",
  "options-script": "Írásjegyek",
  "options-simplified": "Egyszerűsített",
  "options-traditional": "Hagyományos",
  "options-bothscripts": "Mindkettő",
  "options-tonecolors": "Hangsúly szerinti színezés",
  "options-nocolors": "Nincs",
  "options-pleco": "Pleco",
  "options-dummitt": "Dummitt",
  "tooltip-history-comment": "Megjegyzés hozzáfűzése",
  "tooltip-history-edit": "Szócikk szerkesztése",
  "tooltip-history-flag": "Szócikk megjelölése<br/>(pontatlan, téves vagy hiányos)",
  "dialog-ok": "OK",
  "dialog-cancel": "Mégse",
  "history-commententry-title": "Megjegyzés hozzáfűzése",
  "history-commententry-hint": "Írd ide, amit hozzáfűznél a szócikkhez...",
  "history-commententry-successtitle": "Megjegyzés elmentve",
  "history-commententry-successmessage": "A megjegyzésedet sikeresen elmentette a CHDICT. A szócikket a változás-történet első oldalának tetején találod.",
};
